name: payhere_mobilesdk_flutter
description: Make Onetime, Subscription and Pre-approval payments with your Flutter Mobile App through PayHere!
version: 3.0.11
homepage: https://github.com/PayHereLK/payhere-mobilesdk-flutter

environment:
  sdk: ">=2.12.0 <=3.5.4"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: lk.payhere
        pluginClass: PayhereMobilesdkFlutterPlugin
      ios:
        pluginClass: PayhereMobilesdkFlutterPlugin